### ISSUE TITLE
there is no such a file snATACOverlapCounter.jar 

### ISSUE THREAD

**Issue by ChengxiangQiu** [UcarLab/ATAC-DoubletDetector#2]
sorry but I am a little confused that there is no such a file `snATACOverlapCounter.jar` under the GitHub page? how can I generate it? thank you!!

**Comment by ajt986** [comment]
Hello, I've provided the jar files with the zipped release files: https://github.com/UcarLab/ATAC-DoubletDetector/releases I've been trying to avoid putting compiled binaries with the source code.

Best,
Asa
