### ISSUE TITLE
how can I change this parameter MAPQTHRESHOLD=30 to 10?

### ISSUE THREAD

**Issue by ChengxiangQiu** [UcarLab/ATAC-DoubletDetector#3]
how can I change this parameter MAPQTHRESHOLD=30 to 10?

Thank you!

**Comment by ajt986** [comment]
For now, the jar file will need to be recompiled to change this. I'll add ways to set these in a future release soon.  For now I've compiled a version with this set if you want to use this one. 
[snATACOverlapCounter_mq10.jar.zip](https://github.com/UcarLab/ATAC-DoubletDetector/files/5874157/snATACOverlapCounter_mq10.jar.zip)

**Comment by ajt986** [comment]
This option is now added in the latest release.

**Comment by ChengxiangQiu** [comment]
That's great, thank you!
